version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volume/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
networks:
  my_network:
