version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volume/data:/data
    networks:
      - redis-network

  redis-inside:
    image: oblakstudio/redisinsight:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - redis-network
networks:
  redis-network: