version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./volume/data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q status"]
      interval: 20s
      retries: 10
      timeout: 10s
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q kibana"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network

  web:
    image: httpd
    ports:
      - "8123:80"
    depends_on:
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
          fluentd-address: fluentd:24224
          tag: httpd.access
          fluentd-async-connect: "true"
          fluentd-retry-wait: "5s"
          fluentd-max-retries: "5"
          fluentd-sub-second-precision: "true"
          mode: non-blocking

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - app-network

  user-mgt-svc:
    image: nasruddinkhan/user-mgt-svc:0.0.15
    container_name: user-mgt-svc
    ports:
      - "8881:8881"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user-svc?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_PROFILES_ACTIVE=prod
      - LOGGING_LOGSTASH_HOST=fluentd
      - LOGGING_LOGSTASH_PORT=24224
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      mysql:
        condition: service_healthy
      fluentd:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

volumes:
  mysql-data:
  es-data:
  fluentd-log:

networks:
  app-network:
    driver: bridge
